"""Describe your migration here

Revision ID: c217aff2bdb1
Revises: ca6759b9da6d
Create Date: 2024-11-14 02:16:00.599810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c217aff2bdb1'
down_revision = 'ca6759b9da6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_texts', sa.Text(), nullable=False))
        batch_op.drop_column('options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.TEXT(), nullable=False))
        batch_op.drop_column('option_texts')

    # ### end Alembic commands ###
