"""Describe your migration here

Revision ID: ca6759b9da6d
Revises: 
Create Date: 2024-11-14 02:05:37.808544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6759b9da6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('active')
        batch_op.drop_column('options')

    # ### end Alembic commands ###
