"""model update

Revision ID: e007714cc9a4
Revises: c217aff2bdb1
Create Date: 2024-11-14 07:53:01.485435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e007714cc9a4'
down_revision = 'c217aff2bdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('responses',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institute_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institute_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.alter_column('responses',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
